vpd:Overwrite dummy ECC library with the actual one
ibm-openbmc/openbmc pull request #211
Opened 2022-04-25 16:41 UTC by PriyangaRamasamy

This commit installs the actual ecc library in /usr/lib file system
space, which is overwriting the dummy ecc library installed via meson
from the source repository (openpower-vpd-parser).

This is done intentionally to avoid sharing the actual ecc source code
and instead just share the ecc shared library object.

Test:
Tested on rainier.
Corrupted the base panel vpd and checked with ibm-read-vpd app.
With the original ecc library, the error should be thrown and with the dummy
ecc library, no error will be thrown.

Achieving the expected results.

root@rain111bmc:~# ibm-read-vpd --file /sys/bus/i2c/drivers/at24/7-0050/eeprom
ERROR: ECC check did not pass for the Record:VR10
root@rain111bmc:~#

Signed-off-by: Priyanga Ramasamy <priyanga24@in.ibm.com>

2022-04-26 10:41 UTC, jinuthomas approved these changes

2022-04-26 11:03 UTC, santoshpuranik requested changes
The original file has these permissions:
```
~# ls -l /usr/lib/libvpdecc.so.1.0 
-rwxr-xr-x    1 root     root          9488 Apr 25 16:38 /usr/lib/libvpdecc.so.1.0
```
Please use the same when you overwrite the file in do_install:append()

2022-04-28 04:51 UTC, santoshpuranik approved these changes

2022-05-19 15:39 UTC, rfrandse commented
jenkins run tests please

2022-05-25 13:20 UTC, merged