Add TPMDisable interface
ibm-openbmc/openbmc pull request #301
Opened 2023-10-24 02:07 UTC by lxwinspur

IBM has a new requirement to use a new sensor (disable_tpm_sensor) to disable TPM.
This commit adds a sensor named `disable_tpm_sensor` to the ipmi sensor mrw configuration and set `true` by default.

issue: https://github.com/ibm-openbmc/dev/issues/3634

2023-10-24 15:31 UTC, anoo1 requested changes

2023-10-24 15:31 UTC, anoo1 commented on meta-phosphor/recipes-phosphor/ipmi/phosphor-ipmi-sensor-inventory-mrw-config/config.yaml
> +      TPMEnable:
This should be the new TPMDisable?

2023-10-24 15:31 UTC, anoo1 commented on meta-phosphor/recipes-phosphor/settings/phosphor-settings-defaults/defaults.yaml
> +             Default: 'true'
We want the default to be 'false', meaning that the TPM is not disabled by default, only if the customer disables it.

2023-10-25 01:43 UTC, lxwinspur commented
Move to: https://github.com/ibm-openbmc/openbmc/pull/302

2023-10-25 01:43 UTC, closed without merging